"""에러 코드 상수. 응답 본문 `code` 필드 값으로 그대로 사용된다.

규약:
- SCREAMING_SNAKE_CASE
- 도메인_에러유형 형태 (예: SESSION_EXPIRED, MENTORING_NOT_OPEN)
- 한 번 외부에 노출된 코드는 변경 금지(브레이킹 체인지) — 신규 코드 추가는 자유.
"""
from __future__ import annotations

# 인증/세션
SOMA_AUTH_REQUIRED = "SOMA_AUTH_REQUIRED"
SESSION_EXPIRED = "SESSION_EXPIRED"
UPSTREAM_AUTH_FAILED = "UPSTREAM_AUTH_FAILED"

# 입력 검증
INVALID_REQUEST = "INVALID_REQUEST"
VALIDATION_FAILED = "VALIDATION_FAILED"

# 도메인 상태
MENTORING_NOT_OPEN = "MENTORING_NOT_OPEN"

# 업스트림(sidecar/OpenSoma)
UPSTREAM_NOT_FOUND = "UPSTREAM_NOT_FOUND"
UPSTREAM_UNPROCESSABLE = "UPSTREAM_UNPROCESSABLE"
UPSTREAM_UNAVAILABLE = "UPSTREAM_UNAVAILABLE"

# 인프라
DATABASE_UNAVAILABLE = "DATABASE_UNAVAILABLE"
INTERNAL_ERROR = "INTERNAL_ERROR"
